### ISSUE TITLE
[Feat] 돌봄 유형 선택 후 다음 페이지로 넘어가는 기능 활성화/비활성화

### ISSUE THREAD

**Issue by Jiho31** [hinyc/wanted-codestates-project-10-6#37]
### ISSUE
- Group: client
- Type: 
- Detail:

### TODO
 - [x] 리듀서로 상태 관리
 - [x] 돌봄 유형 선택시 주황색 배경 스타일 적용
 - [x] 버튼 활성화되면 주황색 배경 스타일 적용
