### ISSUE TITLE
[Feat] 달력 범위지정 기능 완료 

### ISSUE THREAD

**Issue by juo1221** [hinyc/wanted-codestates-project-10-6#68]
### ISSUE
- Group: client
- Type: 
- Detail:

### TODO
 - [x] 첫 클릭 시 startDay 지정
 - [x] 두번째 클릭 시 endDay지정
 - [x] startDay와 endDay 사이 범위 색깔 표시 
 - [x] startDay와 endDay가 같을 시 HalfBack 제거
